name = "LLVM IR"
grammar = "llvm"
path_suffixes = ["ll"]
line_comments = ["; "]
first_line_pattern = '^;\s*ModuleID\s*='
word_characters = ["."]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
